### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by harshiniks** [Taiwrash/dev-resume#116]
👋 Hi @Taiwrash ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX.

You mentioned in your submission that you wanted to submit a Learn + Collaborate repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a Learn + Collaborate CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

CX Issues

- [ ] Add LEARN.md
- [ ] Add additional Topics
- [ ] Update README
- [ ] Add Code of Conduct
- [ ] Add more issues
- [ ] Add templates for issues

**Comment by Taiwrash** [comment]
@harshiniks Thanks so much for all the work put together in this projects. Thanks and welcome to the world of dev-resume. I am happy to have you here.

But I have the following questions, sometimes ago, somebody suggested converting and migrating the project to ReactJs from HTML, CSS, JAVASCRIPT and ejs. I gave the other to proceed and he is working on the branch right now. Should I do all this instructions for the base project or the migration?

I am very happy seen our project been accepted.

**Comment by Taiwrash** [comment]
Links to the react [Pull Request](https://github.com/Taiwrash/dev-resume/pull/113) and the [Production](https://dev-resume-jkbltsyhw-habeebullahi01.vercel.app/] for perusal.

**Comment by harshiniks** [comment]
> @harshiniks Thanks so much for all the work put together in this projects. Thanks and welcome to the world of dev-resume. I am happy to have you here.
> 
> But I have the following questions, sometimes ago, somebody suggested converting and migrating the project to ReactJs from HTML, CSS, JAVASCRIPT and ejs. I gave the other to proceed and he is working on the branch right now. Should I do all this instructions for the base project or the migration?
> 
> I am very happy seen our project been accepted.

You can decide on what you want to submit in Community exchange with other students. Based on your decision you can add all these info in any of the project you decide to submit.
